# CI_BRANCH is needed by the upstream build script
variables:
  CI_BRANCH: $CI_COMMIT_REF_NAME

# Cache node modules in between jobs
cache:
  key: cache-node_modules
  paths:
  - node_modules/

image: debian:stretch

stages:
  - compile
  - upload

compile:
  stage: compile
  script:
    - apt update
    - apt install --yes curl git make g++ gnupg2
    - ./scripts/bootstrap
    - ./scripts/update-dependencies || true  # maybe the bower deprecation cause a failure
    - ./scripts/build-static -f
    # Move artifacts to our custom dir
    - mkdir -p "${CI_PROJECT_DIR}/compile_artifacts"
    - mv dist/static/* "${CI_PROJECT_DIR}/compile_artifacts"
  artifacts:
    paths:
      - compile_artifacts

upload:
  stage: upload
  script:
  - ./.uploader
