#!/bin/bash
set -e
set -u
set -x

# cd to app root
CWD=$(dirname $0)
if [[ `basename $(pwd)` = 'scripts' ]]; then
  cd ../
else
  cd `dirname $CWD`
fi

echo -n "Installing Submodules..."
git submodule init
git submodule sync
git submodule update
echo "Done"

echo -n "Installing NPM packages..."
# npm ls --global --parseable --long --loglevel info
# npm config set loglevel info
npm install
echo "Done"

echo -n "Installing Bower packages..."
# Try to fix: ESUDO Cannot be run with sudo
bower --allow-root install
echo "Done"
